; PROGRAM TO CONVERT ASCII TO PACKED BCD NUMBER.
; THIS PROGRAM TAKES TWO UNPACKED ASCII NUMBERS (30H TO 39H) AND CONVERTS
; THEM TO A SINGLE PACKED BCD NUMBER. SUCH INPUT IS USUALLY RECEIVED ON THE
; SERIAL PORT FROM USERS.
; A BCD NUMBER 43 WILL BE REPRESENTED AS 34H,33H IN UNPACKED ASCII
; REPRESENTATION.
; TO CONVERT IT TO BCD, SIMPLY SUBTRACT 30H FROM EACH DIGIT. ROTATE THE UPPER
; DIGIT LEFT BY FOUR LOCATIONS AND SUBSTITUTE THE LOWER NIBBLE OF THE BYTE
; WITH THE LOWER DIGIT.
	
COMSEG SEGMENT
	ASSUME CS:COMSEG, DS:COMSEG, SS:COMSEG, ES:COMSEG
	
	ORG 0100H			;ORG FOR COM STRUCTURED PROGRAMS (ALL SEGMENTS IN ONE SEGMENT
						;AND PROGRAM MAXIMUM SIZE 64KBYTES.)
	
START:
	JMP SKIP_DATA		;SKIP OVER DATA DECLARATIONS

;--------------DEFINE DATA SIZES AND NAMES--------

NUM1 DB 36H
NUM2 DB 39H	

;--------------END OF DATA DEFINITION-------------

SKIP_DATA:	
	MOV  AX,11F0H		;Init of SP for Kit
	MOV  SP,AX	
	MOV AX,0000H
	MOV ES,AX
	MOV SS,AX

	PUSH CS			;Init for DS
	POP DS
	
	NOP					
	NOP				
	NOP
	
	MOV AL,BYTE PTR NUM1
	MOV BL,BYTE PTR NUM2
	AND AL,0FH
	AND BL,0FH
	
	MOV CL,04
	ROL AL,CL
	
	OR  AL,BL
	INT 0A5H
	
COMSEG ENDS
END START
