;Program to carry out BCD to Binary conversion.
;THE STORED CONSTANT NUMBER (23) IN THIS CASE IS INTERPRETED BY THE ASSEMBLER
;AS HEX (17). SO THE STORED NUMBER IS 17 (IN THE PROGRAM).
;THE PROGRAM INTERPRETES THIS NUMBER AS DECIMAL.SO THE PROGRAM SEES THIS
;NUMBER AS 17 (BASE 10) WHICH IS EQUIVALENT OF 11 (BASE 16).SO THE FINAL
;ANSWER PRODUCED IS 11.
;E.G. IF THE STORED NUMBER WERE CHANGED TO (SAY) 64. THIS WILL BE STORED AS
;40 (BASE 16) BY THE ASSEMBLER. THE PROGRAM WILL INTERPRET THIS NUMBER AS

; THE BCDBIN PROCEDURE RECEIVES ITS ARGUMENT IN THE AL REGISTER AND THE
; CONVERTED NUMBER IS RETURNED IN THE SAME REGISTER.

COMSEG SEGMENT
	ASSUME CS:COMSEG, DS:COMSEG, SS:COMSEG, ES:COMSEG
	
	ORG 0100H			;ORG FOR COM STRUCTURED PROGRAMS (ALL SEGMENTS IN ONE SEGMENT
						;AND PROGRAM MAXIMUM SIZE 64KbYTES.)
	
START:
	JMP SKIP_DATA		;SKIP OVER DATA DECLARATIONS

;--------------DEFINE DATA SIZES AND NAMES--------

BCD DB 23			;BCD data to be converted to binary
BIN DB ?			;Converted binary data. For input
					;data of 23 the output will be 17 (17h = 23d)

;--------------END OF DATA DEFINITION-------------

SKIP_DATA:
	MOV AX,10FFH
	MOV SP,AX
	
	MOV AX,0000H
	MOV SS,AX
	MOV ES,AX
	
	PUSH CS
	POP DS
	
	NOP
	NOP
	NOP
	
	MOV AL,BCD
	CALL BCDBIN
	
	MOV BIN,AL
	MOV BIN,AL
	INT 0A5H
	
	
	BCDBIN PROC NEAR
	
	PUSHF
	PUSH BX
	PUSH CX
	MOV BL,AL
	AND BL,0FH
	AND AL,0F0H
	MOV CL,04H
	ROR AL,CL
	MOV BH,0AH
	MUL BH
	
	ADD AL,BL
	POP CX
	POP BX
	POPF
	RET
	
	BCDBIN ENDP
	

COMSEG ENDS
END START
	