;SORT A DATA SET USING BUBBLE SORT.
;SORTING IS IN ASCENDING ORDER. i.e. SMALLEST DATA AT TOP AND LARGEST
;DATA AT BOTTOM.
;TO CHANGE THIS BEHAVIOR REVERSE THE ORDER OF OPERANDS FOR CMP INSTRUCTION
;IN THE INLUP.
	
COMSEG SEGMENT
	ASSUME CS:COMSEG, DS:COMSEG, SS:COMSEG, ES:COMSEG
	
	ORG 0100H			;ORG FOR COM STRUCTURED PROGRAMS (ALL SEGMENTS IN ONE SEGMENT
						;AND PROGRAM MAXIMUM SIZE 64KBYTES.)
	
START:
	JMP SKIP_DATA		;SKIP OVER DATA DECLARATIONS

;--------------DEFINE DATA SIZES AND NAMES--------

ARR DW 10H,09H,06H,01H
SIZ DW 4

;--------------END OF DATA DEFINITION-------------	
SKIP_DATA:
	MOV AX,10FFH
	MOV SP,AX
	
	MOV AX,0000H
	MOV SS,AX
	MOV ES,AX
	
	PUSH CS
	POP DS
	
	NOP
	NOP
	NOP	
	
	MOV BX,SIZ
    DEC BX      ;BX=NO OF PASSES NEEDED TO COMPLETE SORTING(N-1) 
OUTLUP: 
    MOV CX,BX   ;CX=NO OF COMPARISIONS TO BE PERFORMED IN A PASS 
    MOV SI,0 
INLUP: 
    MOV AX,ARR[SI] 
    INC SI
	INC SI
    CMP AX,ARR[SI] 
    JB GO_ON 
    XCHG AX,ARR[SI] 
    MOV ARR[SI-2],AX 
GO_ON: 
    LOOP INLUP  ;DEC CX,UNTIL CX=0 
    DEC BX
    JNZ OUTLUP
	INT 0A5H

COMSEG ENDS	
END START
