;TITLE--PROGRAM TO CARRY OUT 32 BIT BY 16 BIT DIVISION USING DIV INSTRUCTION.
	
COMSEG SEGMENT
	ASSUME CS:COMSEG, DS:COMSEG, SS:COMSEG, ES:COMSEG
	
	ORG 0100H			;ORG FOR COM STRUCTURED PROGRAMS (ALL SEGMENTS IN ONE SEGMENT
						;AND PROGRAM MAXIMUM SIZE 64KbYTES.)
	
START:
	JMP SKIP_DATA		;SKIP OVER DATA DECLARATIONS
	
;--------------DEFINE DATA SIZES AND NAMES--------

DIVIDEND  DD 1234567H	;WITH THESE NUMBERS (1234567H AND 2345H) THE ANSWERS
DIVISOR   DW 2345H		;SHOULD BE QUOTIENT = 842H AND REMAINDER = 059DH
QUOTIENT  DW ?			;EXAMINE THESE MEMORY LOCATIONS.
REMAINDER DW ?			

;--------------END OF DATA DEFINITION-------------

SKIP_DATA:

	MOV  AX,11F0H		;Init of SP for Kit
	MOV  SP,AX	
	MOV AX,0000H
	MOV ES,AX
	MOV SS,AX

	PUSH CS			;Init for DS
	POP DS
	
	NOP					
	NOP				
	NOP
	

	MOV AX,WORD PTR DIVIDEND
	MOV DX,WORD PTR DIVIDEND + 2
	MOV BX,DIVISOR


	DIV BX							;PERFORM UNSIGNED DIVISION AX = DX:AX/DIVISOR

	MOV QUOTIENT,AX			;AND DX=REMAINDER (MODULUS OF REMAINDER)
	MOV REMAINDER,DX
	INT 0A5H
	



COMSEG ENDS		;SEGMENT END DECLARED
END START			;PROGRAM END
