;Program to echo a character.
;AFTER SERIAL DOWNLOAD IS COMPLETE, THIS PROGRAM WILL READBACK A CHARACTER
;ON THE CURRENT CONSOLE DEVICE (WHICH IS SERIAL DEVICE IF PROGRAM IS DOWNLOADED
;USING SERIAL PORT), AND THEN WILL ECHO BACK THE CHARACTER. IT WILL CONTINUE
;DOING THIS TILL AN 'A' IS RECEIVED.

; FOR EXAMPLE IF YOU ARE USING HYPERTERMINAL (TURN OFF THE ECHO CHARACTERS
; LOCALLY SETTING UNDER FILE->PROPERTIES->SETTINGS->ASCII SETUP->ECHO TYPED CHARACTERS LOCALLY (DO NOT TICK).
; NOW HYPERTERMINAL WILL NOT SHOW YOU WHAT YOU ARE TYPING UNLESS THE RECEIVING DEVICE SENDS BACK THE CHARACTERS
; (THE KIT MONITOR PRORGRAM IS DESIGNED TO SEND BACK ALL CHARACTERS THAT IT RECEIVES).
; NOW AFTER RUNNING THE PROGRAM, YOU WILL SEE EVERY CHARACTER THAT YOU SEND DOWN THROUGH HYPERTERMINAL USING
; THE PC's KEYBOARD. THIS WILL CONTINUE TILL YOU PRESS 'A'.
; NOW TURN ON THE ECHO TYPED CHARACTERS LOCALLY SETTING, AND RUN THE PROGRAM, YOU SHOULD SEE ALL THE
; CHARACTERS THAT YOU ARE TYPING ECHOED TWICE ON THE HYPERTERMINAL SCREEN.
	
COMSEG SEGMENT
	ASSUME CS:COMSEG, DS:COMSEG, SS:COMSEG, ES:COMSEG
	
	ORG 0100H			;ORG FOR COM STRUCTURED PROGRAMS (ALL SEGMENTS IN ONE SEGMENT
						;AND PROGRAM MAXIMUM SIZE 64KBYTES.)
	
START:
	JMP SKIP_DATA		;SKIP OVER DATA DECLARATIONS

SKIP_DATA:
	MOV AX,10FFH
	MOV SP,AX
	
	MOV AX,0000H
	MOV SS,AX
	MOV ES,AX
	
	PUSH CS
	POP DS
	
	NOP
	NOP
	NOP	
	
ECHOLOOP:
	MOV AH,1
	INT 0A2H		;WAIT FOR CHARACTER ON SERIAL PORT.(INT A2 FUNCTION 1 ON KIT IS GET CHARACTER WITH ECHO)
	CMP AL,41H		;IF RECEIVED CHARACTER IS 'A' EXIT
	JZ ECHODONE
	JMP ECHOLOOP	;ELSE GET NEXT CHARACTER.
	
EchoDone:
	INT 0A5H

COMSEG ENDS
END START
